version: "3.8"

services:

  accounts:
    build: ./accounts
    image: 226772/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - globalbank-network
  loans:
    build: ./loans
    image: 226772/loans:latest
    ports:
      - "8090:8090"
    networks:
      - globalbank-network
  cards:
    build: ./cards
    image: 226772/cards:latest
    ports:
      - "8091:8091"
    networks:
      - globalbank-network
    
networks:
  globalbank-network: